/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Home.Forms.product;

import controller.db.StatementDbSQL;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import view.textPrompt.TextPrompt;

/**
 *
 * @author RODX
 */
public class UpdateProduct_form extends javax.swing.JFrame {
    
    
    //<editor-fold defaultstate="colapsed" desc="* Variables">
    protected StatementDbSQL newStatement = new StatementDbSQL();
    protected String ruta;
    protected boolean AuthVerify = newStatement.getAuthVerify();
    //</editor-fold>

    //<editor-fold defaultstate="colapsed" desc="** Methods">
    public UpdateProduct_form() {
        if (AuthVerify) {
            initComponents();
            this.setLocationRelativeTo(null);

            //PlaceHolders
            TextPrompt PlaceholderId = new TextPrompt("Id/Identidicacion", jTextField_IdProduct);
            TextPrompt PlaceholderName = new TextPrompt("Nombre Producto", jTextField_nameProduct);
            TextPrompt PlaceholderLastName = new TextPrompt("Descripciòn del producto", jTextArea_DescriptionProduct);
            TextPrompt PlaceholderEmail = new TextPrompt("1000,00", jTextField_PriceProduct);
            
        } else {
            JOptionPane.showMessageDialog(null, "Accion no permitida: Usuario no loggeado");
            System.exit(0);
        }
    }

    private byte[] convertImage() {
        File image = new File(ruta);

        try {
            byte[] icon = new byte[(int) image.length()];
            InputStream input = new FileInputStream(image);
            input.read(icon);
            return icon;
        } catch (Exception e) {
            return null;
        }
    }
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrimaryPanel_FormRegisterUser = new javax.swing.JPanel();
        jPanel_registerEmployees = new javax.swing.JPanel();
        jLabel_Exit = new javax.swing.JLabel();
        jLabel_TitlePanelRE = new javax.swing.JLabel();
        jPanel_TextFieldsForm = new javax.swing.JPanel();
        jLabel_TFIdEmployees = new javax.swing.JLabel();
        jTextField_IdProduct = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_TFNameEmployees = new javax.swing.JLabel();
        jTextField_nameProduct = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_TFLastNameEmployees = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel_TFEmailEmployees = new javax.swing.JLabel();
        jTextField_PriceProduct = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_DescriptionProduct = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel_PerfilEmployees = new javax.swing.JLabel();
        jLabel_ButtonSelectImageProduct = new javax.swing.JLabel();
        jLabel_imageLoadProduct = new javax.swing.JLabel();
        jLabel_ButtonSaveDataProduct = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setUndecorated(true);

        jPanel_registerEmployees.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_registerEmployees.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel_registerEmployees.setForeground(java.awt.Color.darkGray);

        jLabel_Exit.setText("X");
        jLabel_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ExitMouseClicked(evt);
            }
        });

        jLabel_TitlePanelRE.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel_TitlePanelRE.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_TitlePanelRE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TitlePanelRE.setText("Actualización Productos");

        jPanel_TextFieldsForm.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_TFIdEmployees.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_TFIdEmployees.setForeground(new java.awt.Color(36, 36, 36));
        jLabel_TFIdEmployees.setText("Id");

        jTextField_IdProduct.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_IdProduct.setBorder(null);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel_TFNameEmployees.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_TFNameEmployees.setForeground(new java.awt.Color(36, 36, 36));
        jLabel_TFNameEmployees.setText("Nombre");

        jTextField_nameProduct.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_nameProduct.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));

        jLabel_TFLastNameEmployees.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_TFLastNameEmployees.setForeground(new java.awt.Color(36, 36, 36));
        jLabel_TFLastNameEmployees.setText("Descripción");

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));

        jLabel_TFEmailEmployees.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_TFEmailEmployees.setForeground(new java.awt.Color(36, 36, 36));
        jLabel_TFEmailEmployees.setText("Precio");

        jTextField_PriceProduct.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_PriceProduct.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));

        jTextArea_DescriptionProduct.setColumns(20);
        jTextArea_DescriptionProduct.setRows(5);
        jScrollPane1.setViewportView(jTextArea_DescriptionProduct);

        javax.swing.GroupLayout jPanel_TextFieldsFormLayout = new javax.swing.GroupLayout(jPanel_TextFieldsForm);
        jPanel_TextFieldsForm.setLayout(jPanel_TextFieldsFormLayout);
        jPanel_TextFieldsFormLayout.setHorizontalGroup(
            jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TextFieldsFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_TextFieldsFormLayout.createSequentialGroup()
                        .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel_TextFieldsFormLayout.createSequentialGroup()
                                    .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_TFNameEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_TFIdEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                    .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_IdProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_nameProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jSeparator1)
                                .addComponent(jSeparator2)
                                .addComponent(jLabel_TFLastNameEmployees, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_TextFieldsFormLayout.createSequentialGroup()
                        .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_TextFieldsFormLayout.createSequentialGroup()
                                .addComponent(jLabel_TFEmailEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_PriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap(7, Short.MAX_VALUE))))
        );
        jPanel_TextFieldsFormLayout.setVerticalGroup(
            jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TextFieldsFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_IdProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TFIdEmployees))
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TFNameEmployees))
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel_TFLastNameEmployees)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TFEmailEmployees)
                    .addComponent(jTextField_PriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_PerfilEmployees.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_PerfilEmployees.setForeground(new java.awt.Color(36, 36, 36));
        jLabel_PerfilEmployees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_PerfilEmployees.setText("Imagen");

        jLabel_ButtonSelectImageProduct.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_ButtonSelectImageProduct.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_ButtonSelectImageProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ButtonSelectImageProduct.setText("seleccionar");
        jLabel_ButtonSelectImageProduct.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jLabel_ButtonSelectImageProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ButtonSelectImageProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ButtonSelectImageProductMouseClicked(evt);
            }
        });

        jLabel_imageLoadProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_imageLoadProduct.setText("No Image");
        jLabel_imageLoadProduct.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_imageLoadProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_PerfilEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel_ButtonSelectImageProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_PerfilEmployees)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_ButtonSelectImageProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_imageLoadProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jLabel_ButtonSaveDataProduct.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_ButtonSaveDataProduct.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_ButtonSaveDataProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ButtonSaveDataProduct.setText("Registrar");
        jLabel_ButtonSaveDataProduct.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jLabel_ButtonSaveDataProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ButtonSaveDataProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ButtonSaveDataProductMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_registerEmployeesLayout = new javax.swing.GroupLayout(jPanel_registerEmployees);
        jPanel_registerEmployees.setLayout(jPanel_registerEmployeesLayout);
        jPanel_registerEmployeesLayout.setHorizontalGroup(
            jPanel_registerEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_registerEmployeesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_TitlePanelRE, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel_Exit)
                .addContainerGap())
            .addGroup(jPanel_registerEmployeesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_TextFieldsForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel_registerEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_registerEmployeesLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel_ButtonSaveDataProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_registerEmployeesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        jPanel_registerEmployeesLayout.setVerticalGroup(
            jPanel_registerEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_registerEmployeesLayout.createSequentialGroup()
                .addGroup(jPanel_registerEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_registerEmployeesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel_TitlePanelRE))
                    .addGroup(jPanel_registerEmployeesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Exit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_registerEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_TextFieldsForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_registerEmployeesLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_ButtonSaveDataProduct)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PrimaryPanel_FormRegisterUserLayout = new javax.swing.GroupLayout(PrimaryPanel_FormRegisterUser);
        PrimaryPanel_FormRegisterUser.setLayout(PrimaryPanel_FormRegisterUserLayout);
        PrimaryPanel_FormRegisterUserLayout.setHorizontalGroup(
            PrimaryPanel_FormRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrimaryPanel_FormRegisterUserLayout.createSequentialGroup()
                .addComponent(jPanel_registerEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PrimaryPanel_FormRegisterUserLayout.setVerticalGroup(
            PrimaryPanel_FormRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrimaryPanel_FormRegisterUserLayout.createSequentialGroup()
                .addComponent(jPanel_registerEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrimaryPanel_FormRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PrimaryPanel_FormRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="colapsed" desc="Event">
    private void jLabel_ButtonSelectImageProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ButtonSelectImageProductMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("jpg, png & gif", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(extensionFilter);
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            ruta = fileChooser.getSelectedFile().getAbsolutePath();
            Image fcImages = new ImageIcon(ruta).getImage();
            ImageIcon iIcFCImage = new ImageIcon(fcImages.getScaledInstance(jLabel_imageLoadProduct.getWidth(), jLabel_imageLoadProduct.getHeight(), 0));
            jLabel_imageLoadProduct.setIcon(iIcFCImage);
            jLabel_imageLoadProduct.setText("");
        }
    }//GEN-LAST:event_jLabel_ButtonSelectImageProductMouseClicked

    private void jLabel_ButtonSaveDataProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ButtonSaveDataProductMouseClicked
        String Id = jTextField_IdProduct.getText(), Name = jTextField_nameProduct.getText(), Descripcion = jTextArea_DescriptionProduct.getText();
        double PriceProduct = Double.parseDouble(jTextField_PriceProduct.getText());
        newStatement.GenerateStatement_UpdateProduct(Integer.parseInt(Id), convertImage(), Name, Descripcion,  PriceProduct);
        JOptionPane.showMessageDialog(null, "Producto Actualizado");
        setVisible(false);
    }//GEN-LAST:event_jLabel_ButtonSaveDataProductMouseClicked

    private void jLabel_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ExitMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jLabel_ExitMouseClicked
    //</editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProduct_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PrimaryPanel_FormRegisterUser;
    private javax.swing.JLabel jLabel_ButtonSaveDataProduct;
    private javax.swing.JLabel jLabel_ButtonSelectImageProduct;
    private javax.swing.JLabel jLabel_Exit;
    private javax.swing.JLabel jLabel_PerfilEmployees;
    private javax.swing.JLabel jLabel_TFEmailEmployees;
    private javax.swing.JLabel jLabel_TFIdEmployees;
    private javax.swing.JLabel jLabel_TFLastNameEmployees;
    private javax.swing.JLabel jLabel_TFNameEmployees;
    private javax.swing.JLabel jLabel_TitlePanelRE;
    private javax.swing.JLabel jLabel_imageLoadProduct;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_TextFieldsForm;
    private javax.swing.JPanel jPanel_registerEmployees;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea_DescriptionProduct;
    private javax.swing.JTextField jTextField_IdProduct;
    private javax.swing.JTextField jTextField_PriceProduct;
    private javax.swing.JTextField jTextField_nameProduct;
    // End of variables declaration//GEN-END:variables
}
