package view.Home;

import controller.db.ConnectionDbSQL;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.ModAdmin.ModAdmin;

/**
 *
 * @author RODX
 */
public class Home extends javax.swing.JFrame {
    
    /**
     * variables declarated from the class - RODX
     */
    boolean StatusMaximize = false;
    public Dimension screenSizeMaximize = Toolkit.getDefaultToolkit().getScreenSize(), screenSizeMinimize;
    public Toolkit tK = Toolkit.getDefaultToolkit();
    protected ModAdmin ModAdminActived = new ModAdmin();
    protected int AxisX, AxisY, AxisXScreen, AxisYScreen;
    
    public Home() {
        initComponents();
        this.screenSizeMinimize = PrimaryPanel_Home.getPreferredSize();
        jPanel_WorkSpaceAdmin.setVisible(false);
    }
    
    /**
     * methods custom
     */
    
    @Override // this method change default icon for Custom Icon
    public Image getIconImage (){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images\\Icons\\1x\\IsoT\\IconBase-Default.png"));
        return retValue;
    }
    
    public void writeTableUser() {
        jTable_Users.getModel();
        
        try {
            ResultSet RSSSQL_Users = ModAdminActived.ModAdmin_GetUsers();    
            DefaultTableModel modelo = new DefaultTableModel();
            jTable_Users.setModel(modelo);
            
            
            modelo.addColumn("ID");
            modelo.addColumn("Perfil");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido");
            modelo.addColumn("Correo");
            modelo.addColumn("Contraseña");
            modelo.addColumn("Direccion");
            modelo.addColumn("Telefono");
            modelo.addColumn("StC");
            modelo.addColumn("StA");
            modelo.addColumn("Genero");
            
            while(RSSSQL_Users.next()){
                Object [] rowUsers = new Object[11];
                for (int i=0;i<11;i++)
                    rowUsers[i] = RSSSQL_Users.getObject(i+1);
                modelo.addRow(rowUsers);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /*
         *ConnectionDbSQL Disconect = new ConnectionDbSQL();
         *Disconect.GenerateDisconnection();
         */
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrimaryPanel_Home = new javax.swing.JPanel();
        jLabel_resizeRight = new javax.swing.JLabel();
        jLabel_resizeLeft = new javax.swing.JLabel();
        jLabel_resizeBottom = new javax.swing.JLabel();
        jLabel_resizeRightBottom = new javax.swing.JLabel();
        jLabel_resizeLeftBottom = new javax.swing.JLabel();
        jPanel_Welcome = new javax.swing.JPanel();
        jLabel_LogoWelcome = new javax.swing.JLabel();
        jLabel_TitleWelcome = new javax.swing.JLabel();
        jLabel_SubtitleWelcome = new javax.swing.JLabel();
        jPanel_BarTop = new javax.swing.JPanel();
        jLabel_ExitButton = new javax.swing.JLabel();
        jLabel_MaxRestore = new javax.swing.JLabel();
        jLabel_Minimize = new javax.swing.JLabel();
        jLabel_DragArea = new javax.swing.JLabel();
        jLabel_LogoScarab = new javax.swing.JLabel();
        jPanel_LeftBar = new javax.swing.JPanel();
        jLabel_ImageUser = new javax.swing.JLabel();
        jLabel_NameUser = new javax.swing.JLabel();
        jSeparator_UserLeverRootDiv = new javax.swing.JSeparator();
        jLabel_LevelAdmin = new javax.swing.JLabel();
        jLabel_AccountingMod = new javax.swing.JLabel();
        jLabel_InventoryMod = new javax.swing.JLabel();
        jLabel_AdminMod = new javax.swing.JLabel();
        jLabel_AcconuntingModLabel = new javax.swing.JLabel();
        jLabel_InvetoryModLabel = new javax.swing.JLabel();
        jLabel_AdminModLabel = new javax.swing.JLabel();
        jPanel_WorkSpaceAdmin = new javax.swing.JPanel();
        jPanel_BarToolAdmin = new javax.swing.JPanel();
        jLabel_ButtonQueryUser = new javax.swing.JLabel();
        jPanel_SpaceAdmin = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Users = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scarab - Home");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(1980, 1080));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Home"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1100, 728));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PrimaryPanel_Home.setBackground(new java.awt.Color(51, 51, 51));
        PrimaryPanel_Home.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(102, 102, 102)));
        PrimaryPanel_Home.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PrimaryPanel_Home.setMaximumSize(new java.awt.Dimension(1920, 1080));
        PrimaryPanel_Home.setMinimumSize(new java.awt.Dimension(800, 600));
        PrimaryPanel_Home.setName("Home"); // NOI18N
        PrimaryPanel_Home.setPreferredSize(new java.awt.Dimension(1100, 728));

        jLabel_resizeRight.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_resizeRight.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));

        jLabel_resizeLeft.setBackground(new java.awt.Color(153, 255, 255));
        jLabel_resizeLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));

        jLabel_resizeBottom.setBackground(new java.awt.Color(153, 255, 255));
        jLabel_resizeBottom.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));

        jLabel_resizeRightBottom.setBackground(new java.awt.Color(0, 153, 153));
        jLabel_resizeRightBottom.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));

        jLabel_resizeLeftBottom.setBackground(new java.awt.Color(0, 153, 153));
        jLabel_resizeLeftBottom.setCursor(new java.awt.Cursor(java.awt.Cursor.SW_RESIZE_CURSOR));

        jPanel_Welcome.setBackground(new java.awt.Color(51, 51, 51));

        jLabel_LogoWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconBase-Default.png"))); // NOI18N

        jLabel_TitleWelcome.setFont(new java.awt.Font("Bebas Neue", 1, 48)); // NOI18N
        jLabel_TitleWelcome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TitleWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TitleWelcome.setText("Bienvenido a Scarab");
        jLabel_TitleWelcome.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel_SubtitleWelcome.setFont(new java.awt.Font("Bebas Neue Light", 0, 24)); // NOI18N
        jLabel_SubtitleWelcome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_SubtitleWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_SubtitleWelcome.setText("Sistema Contable y Administrativo");
        jLabel_SubtitleWelcome.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel_WelcomeLayout = new javax.swing.GroupLayout(jPanel_Welcome);
        jPanel_Welcome.setLayout(jPanel_WelcomeLayout);
        jPanel_WelcomeLayout.setHorizontalGroup(
            jPanel_WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_WelcomeLayout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jLabel_LogoWelcome)
                .addGap(1, 1, 1)
                .addGroup(jPanel_WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_TitleWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jLabel_SubtitleWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel_WelcomeLayout.setVerticalGroup(
            jPanel_WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_WelcomeLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(jPanel_WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel_WelcomeLayout.createSequentialGroup()
                        .addComponent(jLabel_TitleWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_SubtitleWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_LogoWelcome))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jPanel_BarTop.setBackground(new java.awt.Color(38, 38, 38));
        jPanel_BarTop.setAutoscrolls(true);
        jPanel_BarTop.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel_ExitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ExitButton.setText("X");
        jLabel_ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ExitButtonMouseClicked(evt);
            }
        });

        jLabel_MaxRestore.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_MaxRestore.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_MaxRestore.setText("❐");
        jLabel_MaxRestore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MaxRestoreMouseClicked(evt);
            }
        });

        jLabel_Minimize.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Minimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Minimize.setText("-");
        jLabel_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseClicked(evt);
            }
        });

        jLabel_DragArea.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel_DragAreaMouseDragged(evt);
            }
        });
        jLabel_DragArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_DragAreaMousePressed(evt);
            }
        });

        jLabel_LogoScarab.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel_LogoScarab.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_LogoScarab.setIcon(new javax.swing.ImageIcon("E:\\Programacion\\JavaProjets\\SysScarab\\src\\main\\resources\\images\\Icons\\1x\\IsoT\\Icon-20px.png")); // NOI18N
        jLabel_LogoScarab.setText("SCARAB");
        jLabel_LogoScarab.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        javax.swing.GroupLayout jPanel_BarTopLayout = new javax.swing.GroupLayout(jPanel_BarTop);
        jPanel_BarTop.setLayout(jPanel_BarTopLayout);
        jPanel_BarTopLayout.setHorizontalGroup(
            jPanel_BarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BarTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_LogoScarab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_DragArea, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Minimize)
                .addGap(18, 18, 18)
                .addComponent(jLabel_MaxRestore)
                .addGap(18, 18, 18)
                .addComponent(jLabel_ExitButton)
                .addGap(18, 18, 18))
        );
        jPanel_BarTopLayout.setVerticalGroup(
            jPanel_BarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BarTopLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_LogoScarab)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BarTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_BarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_MaxRestore)
                        .addComponent(jLabel_ExitButton)
                        .addComponent(jLabel_Minimize))
                    .addComponent(jLabel_DragArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel_LeftBar.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_LeftBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_ImageUser.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_ImageUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ImageUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ImageUser.setText("ImageProfileUnloaded");
        jLabel_ImageUser.setOpaque(true);

        jLabel_NameUser.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_NameUser.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        jLabel_NameUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NameUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_NameUser.setText("User");

        jSeparator_UserLeverRootDiv.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_LevelAdmin.setFont(new java.awt.Font("Roboto Mono Thin", 2, 12)); // NOI18N
        jLabel_LevelAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_LevelAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_LevelAdmin.setText("StatusAdmim");

        jLabel_AccountingMod.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_AccountingMod.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_AccountingMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_AccountingMod.setIcon(new javax.swing.ImageIcon("E:\\Programacion\\JavaProjets\\SysScarab\\src\\main\\resources\\images\\Icons\\1x\\IconAccounting.png")); // NOI18N

        jLabel_InventoryMod.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_InventoryMod.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_InventoryMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_InventoryMod.setIcon(new javax.swing.ImageIcon("E:\\Programacion\\JavaProjets\\SysScarab\\src\\main\\resources\\images\\Icons\\1x\\IconInventoy.png")); // NOI18N

        jLabel_AdminMod.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_AdminMod.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_AdminMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_AdminMod.setIcon(new javax.swing.ImageIcon("E:\\Programacion\\JavaProjets\\SysScarab\\src\\main\\resources\\images\\Icons\\1x\\IconManagement.png")); // NOI18N
        jLabel_AdminMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_AdminModMouseClicked(evt);
            }
        });

        jLabel_AcconuntingModLabel.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_AcconuntingModLabel.setForeground(new java.awt.Color(153, 255, 153));
        jLabel_AcconuntingModLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_AcconuntingModLabel.setText("Contabilidad");

        jLabel_InvetoryModLabel.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_InvetoryModLabel.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_InvetoryModLabel.setForeground(new java.awt.Color(204, 153, 255));
        jLabel_InvetoryModLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_InvetoryModLabel.setText("Inventario");

        jLabel_AdminModLabel.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_AdminModLabel.setForeground(new java.awt.Color(255, 153, 153));
        jLabel_AdminModLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_AdminModLabel.setText("Administracion");

        javax.swing.GroupLayout jPanel_LeftBarLayout = new javax.swing.GroupLayout(jPanel_LeftBar);
        jPanel_LeftBar.setLayout(jPanel_LeftBarLayout);
        jPanel_LeftBarLayout.setHorizontalGroup(
            jPanel_LeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LeftBarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel_LeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_AccountingMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_ImageUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_NameUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator_UserLeverRootDiv, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_LevelAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_AcconuntingModLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
            .addGroup(jPanel_LeftBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_LeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_LeftBarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel_InventoryMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel_InvetoryModLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel_LeftBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_LeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_AdminMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_AdminModLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_LeftBarLayout.setVerticalGroup(
            jPanel_LeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LeftBarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel_ImageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_NameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator_UserLeverRootDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_LevelAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_AccountingMod, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_AcconuntingModLabel)
                .addGap(12, 12, 12)
                .addComponent(jLabel_InventoryMod, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_InvetoryModLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_AdminMod, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_AdminModLabel)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel_WorkSpaceAdmin.setBackground(new java.awt.Color(51, 51, 51));

        jPanel_BarToolAdmin.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_BarToolAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_ButtonQueryUser.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_ButtonQueryUser.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel_ButtonQueryUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ButtonQueryUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ButtonQueryUser.setText(" Consultar Usuarios ");
        jLabel_ButtonQueryUser.setToolTipText("");
        jLabel_ButtonQueryUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_ButtonQueryUser.setOpaque(true);
        jLabel_ButtonQueryUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ButtonQueryUserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_BarToolAdminLayout = new javax.swing.GroupLayout(jPanel_BarToolAdmin);
        jPanel_BarToolAdmin.setLayout(jPanel_BarToolAdminLayout);
        jPanel_BarToolAdminLayout.setHorizontalGroup(
            jPanel_BarToolAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BarToolAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_ButtonQueryUser, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_BarToolAdminLayout.setVerticalGroup(
            jPanel_BarToolAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BarToolAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_ButtonQueryUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jPanel_SpaceAdmin.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_SpaceAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable_Users.setBackground(new java.awt.Color(204, 204, 204));
        jTable_Users.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        jTable_Users.setModel(jTable_Users.getModel());
        jScrollPane1.setViewportView(jTable_Users);

        javax.swing.GroupLayout jPanel_SpaceAdminLayout = new javax.swing.GroupLayout(jPanel_SpaceAdmin);
        jPanel_SpaceAdmin.setLayout(jPanel_SpaceAdminLayout);
        jPanel_SpaceAdminLayout.setHorizontalGroup(
            jPanel_SpaceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_SpaceAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_SpaceAdminLayout.setVerticalGroup(
            jPanel_SpaceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SpaceAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_WorkSpaceAdminLayout = new javax.swing.GroupLayout(jPanel_WorkSpaceAdmin);
        jPanel_WorkSpaceAdmin.setLayout(jPanel_WorkSpaceAdminLayout);
        jPanel_WorkSpaceAdminLayout.setHorizontalGroup(
            jPanel_WorkSpaceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_BarToolAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_SpaceAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_WorkSpaceAdminLayout.setVerticalGroup(
            jPanel_WorkSpaceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_WorkSpaceAdminLayout.createSequentialGroup()
                .addComponent(jPanel_BarToolAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_SpaceAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PrimaryPanel_HomeLayout = new javax.swing.GroupLayout(PrimaryPanel_Home);
        PrimaryPanel_Home.setLayout(PrimaryPanel_HomeLayout);
        PrimaryPanel_HomeLayout.setHorizontalGroup(
            PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrimaryPanel_HomeLayout.createSequentialGroup()
                .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_resizeLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jLabel_resizeLeftBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrimaryPanel_HomeLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPanel_LeftBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_WorkSpaceAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PrimaryPanel_HomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_resizeBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_resizeRight, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_resizeRightBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jPanel_BarTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PrimaryPanel_HomeLayout.createSequentialGroup()
                    .addGap(166, 166, 166)
                    .addComponent(jPanel_Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(15, 15, 15)))
        );
        PrimaryPanel_HomeLayout.setVerticalGroup(
            PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrimaryPanel_HomeLayout.createSequentialGroup()
                .addComponent(jPanel_BarTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_resizeLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_resizeRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_LeftBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_WorkSpaceAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel_resizeRightBottom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jLabel_resizeLeftBottom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jLabel_resizeBottom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PrimaryPanel_HomeLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jPanel_Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        getContentPane().add(PrimaryPanel_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_DragAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_DragAreaMousePressed
        // TODO add your handling code here:
        AxisY = evt.getY();
        AxisX = evt.getX();
    }//GEN-LAST:event_jLabel_DragAreaMousePressed

    private void jLabel_DragAreaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_DragAreaMouseDragged
        // TODO add your handling code here:
        AxisXScreen = evt.getXOnScreen();
        AxisYScreen = evt.getYOnScreen();
        this.setLocation(AxisXScreen - AxisX, AxisYScreen - AxisY);
    }//GEN-LAST:event_jLabel_DragAreaMouseDragged

    private void jLabel_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(1);
        
        if(!StatusMaximize){
            PrimaryPanel_Home.setPreferredSize(screenSizeMaximize);
        }
        else{
            PrimaryPanel_Home.setPreferredSize(screenSizeMinimize);
        }
    }//GEN-LAST:event_jLabel_MinimizeMouseClicked

    private void jLabel_MaxRestoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MaxRestoreMouseClicked
        // TODO add your handling code here:
        if(!StatusMaximize){
            this.setExtendedState(this.MAXIMIZED_BOTH);
            PrimaryPanel_Home.setPreferredSize(screenSizeMaximize);
            StatusMaximize = true;
        }
        else{
            this.setExtendedState(this.NORMAL);
            PrimaryPanel_Home.setPreferredSize(screenSizeMinimize);
            StatusMaximize = false;
        }
    }//GEN-LAST:event_jLabel_MaxRestoreMouseClicked

    private void jLabel_ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ExitButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel_ExitButtonMouseClicked

    private void jLabel_AdminModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AdminModMouseClicked
        // TODO add your handling code here:
        jPanel_WorkSpaceAdmin.setVisible(true);
        jPanel_Welcome.setVisible(false);
    }//GEN-LAST:event_jLabel_AdminModMouseClicked

    private void jLabel_ButtonQueryUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ButtonQueryUserMouseClicked
        // TODO add your handling code here:
        writeTableUser();
    }//GEN-LAST:event_jLabel_ButtonQueryUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PrimaryPanel_Home;
    private javax.swing.JLabel jLabel_AcconuntingModLabel;
    private javax.swing.JLabel jLabel_AccountingMod;
    private javax.swing.JLabel jLabel_AdminMod;
    private javax.swing.JLabel jLabel_AdminModLabel;
    private javax.swing.JLabel jLabel_ButtonQueryUser;
    private javax.swing.JLabel jLabel_DragArea;
    private javax.swing.JLabel jLabel_ExitButton;
    private javax.swing.JLabel jLabel_ImageUser;
    private javax.swing.JLabel jLabel_InventoryMod;
    private javax.swing.JLabel jLabel_InvetoryModLabel;
    private javax.swing.JLabel jLabel_LevelAdmin;
    private javax.swing.JLabel jLabel_LogoScarab;
    private javax.swing.JLabel jLabel_LogoWelcome;
    private javax.swing.JLabel jLabel_MaxRestore;
    private javax.swing.JLabel jLabel_Minimize;
    private javax.swing.JLabel jLabel_NameUser;
    private javax.swing.JLabel jLabel_SubtitleWelcome;
    private javax.swing.JLabel jLabel_TitleWelcome;
    private javax.swing.JLabel jLabel_resizeBottom;
    private javax.swing.JLabel jLabel_resizeLeft;
    private javax.swing.JLabel jLabel_resizeLeftBottom;
    private javax.swing.JLabel jLabel_resizeRight;
    private javax.swing.JLabel jLabel_resizeRightBottom;
    private javax.swing.JPanel jPanel_BarToolAdmin;
    private javax.swing.JPanel jPanel_BarTop;
    private javax.swing.JPanel jPanel_LeftBar;
    private javax.swing.JPanel jPanel_SpaceAdmin;
    private javax.swing.JPanel jPanel_Welcome;
    private javax.swing.JPanel jPanel_WorkSpaceAdmin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator_UserLeverRootDiv;
    private javax.swing.JTable jTable_Users;
    // End of variables declaration//GEN-END:variables
}
