package view.Home;

import controller.db.StatementDbSQL;
import javax.swing.table.DefaultTableModel;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import controller.user.authenticationUser.AuthenticationUser;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.reports.GenerateReport;
import view.Home.Forms.RegisterUser_form;
import view.Home.Forms.UpdateUser_form;
import view.Login.Login;
import view.RenderImageTable;

/**
 *
 * @author RODX
 */
public final class Home extends javax.swing.JFrame {

    //<editor-fold defaultstate="colapsed" desc="* Variables">
    public boolean StatusMaximize = false;
    public Dimension screenSizeMaximize = Toolkit.getDefaultToolkit().getScreenSize(), screenSizeMinimize;
    public Toolkit tK = Toolkit.getDefaultToolkit();
    protected int AxisX, AxisY, AxisXScreen, AxisYScreen;
    protected StatementDbSQL stDb = new StatementDbSQL();
    protected boolean AuthVerify = stDb.getAuthVerify();

    private Object ValuePointSelectedDeleteTable;
    //</editor-fold>    

    //<editor-fold defaultstate="colapsed" desc="** Getters & Setters / Constructors">
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.screenSizeMinimize = PrimaryPanel_Home.getPreferredSize();
        jPanel_WorkSpaceAdmin.setVisible(false);
    }
    
    @Override // this method change default icon for Custom Icon
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images\\Icons\\1x\\IsoT\\IconBase-Default.png"));
        return retValue;
    }
    //</editor-fold>

    //<editor-fold defaultstate="colapsed" desc="*** Methods">

    public DefaultTableModel CreateModelTableEmployees() {
        DefaultTableModel modelTable = new DefaultTableModel();;
        jTable_TableAdminSQL.getModel();
        jTable_TableAdminSQL.setModel(modelTable);
        modelTable.addColumn("ID");
        modelTable.addColumn("Perfil");
        modelTable.addColumn("Nombre");
        modelTable.addColumn("Apellido");
        modelTable.addColumn("Correo");
        modelTable.addColumn("Contraseña");
        modelTable.addColumn("Telefono");
        modelTable.addColumn("StA");
        modelTable.addColumn("StC");
        modelTable.addColumn("Genero");
        return modelTable;
    }

    public void writeDataUserLogged() {
        Map<String, Object> MapDataUserLogged = new HashMap<>();
        AuthenticationUser getDataAuth = new AuthenticationUser();
        MapDataUserLogged = getDataAuth.GetDataUser();

        jLabel_NameUser.setText((String) MapDataUserLogged.get("nameEmployees"));

        switch ((String) MapDataUserLogged.get("StatusAdminEmployees")) {
            case "EP":
                jLabel_LevelAdmin.setText("Empleado");
            case "AD":
                jLabel_LevelAdmin.setText("Administrador");
            case "NA":
                jLabel_LevelAdmin.setText("No Usuario");
        }
    }
    //</editor-fold>
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrimaryPanel_Home = new javax.swing.JPanel();
        jLabel_resizeRight = new javax.swing.JLabel();
        jLabel_resizeLeft = new javax.swing.JLabel();
        jLabel_resizeBottom = new javax.swing.JLabel();
        jLabel_resizeRightBottom = new javax.swing.JLabel();
        jLabel_resizeLeftBottom = new javax.swing.JLabel();
        jPanel_Welcome = new javax.swing.JPanel();
        jLabel_LogoWelcome = new javax.swing.JLabel();
        jLabel_TitleWelcome = new javax.swing.JLabel();
        jLabel_SubtitleWelcome = new javax.swing.JLabel();
        jPanel_BarTop = new javax.swing.JPanel();
        jLabel_ExitButton = new javax.swing.JLabel();
        jLabel_MaxRestore = new javax.swing.JLabel();
        jLabel_Minimize = new javax.swing.JLabel();
        jLabel_DragArea = new javax.swing.JLabel();
        jLabel_LogoScarab = new javax.swing.JLabel();
        jPanel_LeftBar = new javax.swing.JPanel();
        jLabel_NameUser = new javax.swing.JLabel();
        jSeparator_UserLeverRootDiv = new javax.swing.JSeparator();
        jLabel_LevelAdmin = new javax.swing.JLabel();
        jLabel_AccountingMod = new javax.swing.JLabel();
        jLabel_InventoryMod = new javax.swing.JLabel();
        jLabel_AdminMod = new javax.swing.JLabel();
        jLabel_AcconuntingModLabel = new javax.swing.JLabel();
        jLabel_InvetoryModLabel = new javax.swing.JLabel();
        jLabel_AdminModLabel = new javax.swing.JLabel();
        jLabel_ButtonLogOut = new javax.swing.JLabel();
        jPanel_WorkSpaceAdmin = new javax.swing.JPanel();
        jPanel_BarToolAdmin = new javax.swing.JPanel();
        jLabel_ButtonGetEmployees = new javax.swing.JLabel();
        jLabel_ButtonSetEmployees = new javax.swing.JLabel();
        jLabel_ButtonUpdateUser = new javax.swing.JLabel();
        jLabel_ButtonGenerateReport = new javax.swing.JLabel();
        jPanel_SpaceAdmin = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_TableAdminSQL = new javax.swing.JTable();
        jLabel_ButtonCleanTable = new javax.swing.JLabel();
        jLabel_ButtonDeleteEntities = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scarab - Home");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(1980, 1080));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Home"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PrimaryPanel_Home.setBackground(new java.awt.Color(51, 51, 51));
        PrimaryPanel_Home.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PrimaryPanel_Home.setMaximumSize(new java.awt.Dimension(1920, 1080));
        PrimaryPanel_Home.setMinimumSize(new java.awt.Dimension(800, 600));
        PrimaryPanel_Home.setName("Home"); // NOI18N
        PrimaryPanel_Home.setPreferredSize(new java.awt.Dimension(1100, 728));

        jLabel_resizeRight.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_resizeRight.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));

        jLabel_resizeLeft.setBackground(new java.awt.Color(153, 255, 255));
        jLabel_resizeLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));

        jLabel_resizeBottom.setBackground(new java.awt.Color(153, 255, 255));
        jLabel_resizeBottom.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));

        jLabel_resizeRightBottom.setBackground(new java.awt.Color(0, 153, 153));
        jLabel_resizeRightBottom.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));

        jLabel_resizeLeftBottom.setBackground(new java.awt.Color(0, 153, 153));
        jLabel_resizeLeftBottom.setCursor(new java.awt.Cursor(java.awt.Cursor.SW_RESIZE_CURSOR));

        jPanel_Welcome.setBackground(new java.awt.Color(51, 51, 51));

        jLabel_LogoWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconBase-Default.png"))); // NOI18N

        jLabel_TitleWelcome.setFont(new java.awt.Font("Bebas Neue", 1, 48)); // NOI18N
        jLabel_TitleWelcome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TitleWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TitleWelcome.setText("Bienvenido a Scarab");
        jLabel_TitleWelcome.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel_SubtitleWelcome.setFont(new java.awt.Font("Bebas Neue Light", 0, 24)); // NOI18N
        jLabel_SubtitleWelcome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_SubtitleWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_SubtitleWelcome.setText("Sistema Contable y Administrativo");
        jLabel_SubtitleWelcome.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel_WelcomeLayout = new javax.swing.GroupLayout(jPanel_Welcome);
        jPanel_Welcome.setLayout(jPanel_WelcomeLayout);
        jPanel_WelcomeLayout.setHorizontalGroup(
            jPanel_WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_WelcomeLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(jLabel_LogoWelcome)
                .addGap(1, 1, 1)
                .addGroup(jPanel_WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_TitleWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jLabel_SubtitleWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel_WelcomeLayout.setVerticalGroup(
            jPanel_WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_WelcomeLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(jPanel_WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel_WelcomeLayout.createSequentialGroup()
                        .addComponent(jLabel_TitleWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_SubtitleWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_LogoWelcome))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jPanel_BarTop.setBackground(new java.awt.Color(38, 38, 38));
        jPanel_BarTop.setAutoscrolls(true);
        jPanel_BarTop.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel_ExitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ExitButton.setText("X");
        jLabel_ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ExitButtonMouseClicked(evt);
            }
        });

        jLabel_MaxRestore.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_MaxRestore.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_MaxRestore.setText("❐");
        jLabel_MaxRestore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MaxRestoreMouseClicked(evt);
            }
        });

        jLabel_Minimize.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Minimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Minimize.setText("-");
        jLabel_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseClicked(evt);
            }
        });

        jLabel_DragArea.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel_DragAreaMouseDragged(evt);
            }
        });
        jLabel_DragArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_DragAreaMousePressed(evt);
            }
        });

        jLabel_LogoScarab.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel_LogoScarab.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_LogoScarab.setText("SCARAB");
        jLabel_LogoScarab.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        javax.swing.GroupLayout jPanel_BarTopLayout = new javax.swing.GroupLayout(jPanel_BarTop);
        jPanel_BarTop.setLayout(jPanel_BarTopLayout);
        jPanel_BarTopLayout.setHorizontalGroup(
            jPanel_BarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BarTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_LogoScarab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_DragArea, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Minimize)
                .addGap(18, 18, 18)
                .addComponent(jLabel_MaxRestore)
                .addGap(18, 18, 18)
                .addComponent(jLabel_ExitButton)
                .addGap(18, 18, 18))
        );
        jPanel_BarTopLayout.setVerticalGroup(
            jPanel_BarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BarTopLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_LogoScarab)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BarTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_BarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_MaxRestore)
                        .addComponent(jLabel_ExitButton)
                        .addComponent(jLabel_Minimize))
                    .addComponent(jLabel_DragArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel_LeftBar.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_LeftBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_NameUser.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_NameUser.setFont(new java.awt.Font("Roboto Thin", 0, 12)); // NOI18N
        jLabel_NameUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NameUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_NameUser.setText("User");

        jSeparator_UserLeverRootDiv.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_LevelAdmin.setFont(new java.awt.Font("Roboto Mono Thin", 2, 12)); // NOI18N
        jLabel_LevelAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_LevelAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_LevelAdmin.setText("StatusAdmim");

        jLabel_AccountingMod.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_AccountingMod.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_AccountingMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_AccountingMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/1x/IconAccounting.png"))); // NOI18N

        jLabel_InventoryMod.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_InventoryMod.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_InventoryMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_InventoryMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/1x/IconInventoy.png"))); // NOI18N

        jLabel_AdminMod.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_AdminMod.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_AdminMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_AdminMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/1x/IconManagement.png"))); // NOI18N
        jLabel_AdminMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_AdminModMouseClicked(evt);
            }
        });

        jLabel_AcconuntingModLabel.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_AcconuntingModLabel.setForeground(new java.awt.Color(153, 255, 153));
        jLabel_AcconuntingModLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_AcconuntingModLabel.setText("Contabilidad");

        jLabel_InvetoryModLabel.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_InvetoryModLabel.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_InvetoryModLabel.setForeground(new java.awt.Color(204, 153, 255));
        jLabel_InvetoryModLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_InvetoryModLabel.setText("Inventario");

        jLabel_AdminModLabel.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_AdminModLabel.setForeground(new java.awt.Color(255, 153, 153));
        jLabel_AdminModLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_AdminModLabel.setText("Administracion");

        jLabel_ButtonLogOut.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_ButtonLogOut.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel_ButtonLogOut.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ButtonLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ButtonLogOut.setText("Cerrar Sesión");
        jLabel_ButtonLogOut.setToolTipText("");
        jLabel_ButtonLogOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_ButtonLogOut.setOpaque(true);
        jLabel_ButtonLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ButtonLogOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_LeftBarLayout = new javax.swing.GroupLayout(jPanel_LeftBar);
        jPanel_LeftBar.setLayout(jPanel_LeftBarLayout);
        jPanel_LeftBarLayout.setHorizontalGroup(
            jPanel_LeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LeftBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_LeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_InvetoryModLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_AdminMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_AdminModLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_LeftBarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel_LeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_AccountingMod, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jLabel_AcconuntingModLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_InventoryMod, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LeftBarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel_LeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_NameUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator_UserLeverRootDiv)
                    .addComponent(jLabel_LevelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
            .addGroup(jPanel_LeftBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_ButtonLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_LeftBarLayout.setVerticalGroup(
            jPanel_LeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LeftBarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel_NameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator_UserLeverRootDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_LevelAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_AccountingMod, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_AcconuntingModLabel)
                .addGap(27, 27, 27)
                .addComponent(jLabel_InventoryMod, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_InvetoryModLabel)
                .addGap(27, 27, 27)
                .addComponent(jLabel_AdminMod, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_AdminModLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_ButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_WorkSpaceAdmin.setBackground(new java.awt.Color(51, 51, 51));

        jPanel_BarToolAdmin.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_BarToolAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_ButtonGetEmployees.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_ButtonGetEmployees.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel_ButtonGetEmployees.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ButtonGetEmployees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ButtonGetEmployees.setText(" Consultar Usuarios ");
        jLabel_ButtonGetEmployees.setToolTipText("");
        jLabel_ButtonGetEmployees.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_ButtonGetEmployees.setOpaque(true);
        jLabel_ButtonGetEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ButtonGetEmployeesMouseClicked(evt);
            }
        });

        jLabel_ButtonSetEmployees.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_ButtonSetEmployees.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel_ButtonSetEmployees.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ButtonSetEmployees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ButtonSetEmployees.setText(" Agregar Usuarios ");
        jLabel_ButtonSetEmployees.setToolTipText("");
        jLabel_ButtonSetEmployees.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_ButtonSetEmployees.setOpaque(true);
        jLabel_ButtonSetEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ButtonSetEmployeesMouseClicked(evt);
            }
        });

        jLabel_ButtonUpdateUser.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_ButtonUpdateUser.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel_ButtonUpdateUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ButtonUpdateUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ButtonUpdateUser.setText("Actualizar Usuarios");
        jLabel_ButtonUpdateUser.setToolTipText("");
        jLabel_ButtonUpdateUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_ButtonUpdateUser.setOpaque(true);
        jLabel_ButtonUpdateUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ButtonUpdateUserMouseClicked(evt);
            }
        });

        jLabel_ButtonGenerateReport.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_ButtonGenerateReport.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel_ButtonGenerateReport.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ButtonGenerateReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ButtonGenerateReport.setText("Reporte Usuarios-Log");
        jLabel_ButtonGenerateReport.setToolTipText("");
        jLabel_ButtonGenerateReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_ButtonGenerateReport.setOpaque(true);
        jLabel_ButtonGenerateReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ButtonGenerateReportMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_BarToolAdminLayout = new javax.swing.GroupLayout(jPanel_BarToolAdmin);
        jPanel_BarToolAdmin.setLayout(jPanel_BarToolAdminLayout);
        jPanel_BarToolAdminLayout.setHorizontalGroup(
            jPanel_BarToolAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BarToolAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_BarToolAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_ButtonGetEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ButtonSetEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ButtonUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ButtonGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_BarToolAdminLayout.setVerticalGroup(
            jPanel_BarToolAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BarToolAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_ButtonGetEmployees)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_ButtonSetEmployees)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_ButtonUpdateUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_ButtonGenerateReport)
                .addContainerGap())
        );

        jPanel_SpaceAdmin.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_SpaceAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable_TableAdminSQL.setBackground(new java.awt.Color(255, 255, 255));
        jTable_TableAdminSQL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTable_TableAdminSQL.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        jTable_TableAdminSQL.setModel(jTable_TableAdminSQL.getModel());
        jTable_TableAdminSQL.setRowHeight(60);
        jTable_TableAdminSQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_TableAdminSQLMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_TableAdminSQL);

        jLabel_ButtonCleanTable.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_ButtonCleanTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ButtonCleanTable.setText("Limpiar");
        jLabel_ButtonCleanTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jLabel_ButtonCleanTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ButtonCleanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ButtonCleanTableMouseClicked(evt);
            }
        });

        jLabel_ButtonDeleteEntities.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_ButtonDeleteEntities.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ButtonDeleteEntities.setText("Eliminar");
        jLabel_ButtonDeleteEntities.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jLabel_ButtonDeleteEntities.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ButtonDeleteEntities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ButtonDeleteEntitiesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_SpaceAdminLayout = new javax.swing.GroupLayout(jPanel_SpaceAdmin);
        jPanel_SpaceAdmin.setLayout(jPanel_SpaceAdminLayout);
        jPanel_SpaceAdminLayout.setHorizontalGroup(
            jPanel_SpaceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_SpaceAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SpaceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel_SpaceAdminLayout.createSequentialGroup()
                        .addGap(0, 762, Short.MAX_VALUE)
                        .addComponent(jLabel_ButtonDeleteEntities, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_ButtonCleanTable, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_SpaceAdminLayout.setVerticalGroup(
            jPanel_SpaceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_SpaceAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_SpaceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ButtonCleanTable, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ButtonDeleteEntities, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_WorkSpaceAdminLayout = new javax.swing.GroupLayout(jPanel_WorkSpaceAdmin);
        jPanel_WorkSpaceAdmin.setLayout(jPanel_WorkSpaceAdminLayout);
        jPanel_WorkSpaceAdminLayout.setHorizontalGroup(
            jPanel_WorkSpaceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_BarToolAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_SpaceAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_WorkSpaceAdminLayout.setVerticalGroup(
            jPanel_WorkSpaceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_WorkSpaceAdminLayout.createSequentialGroup()
                .addComponent(jPanel_BarToolAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_SpaceAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PrimaryPanel_HomeLayout = new javax.swing.GroupLayout(PrimaryPanel_Home);
        PrimaryPanel_Home.setLayout(PrimaryPanel_HomeLayout);
        PrimaryPanel_HomeLayout.setHorizontalGroup(
            PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrimaryPanel_HomeLayout.createSequentialGroup()
                .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_resizeLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jLabel_resizeLeftBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrimaryPanel_HomeLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPanel_LeftBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_WorkSpaceAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PrimaryPanel_HomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_resizeBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_resizeRight, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_resizeRightBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jPanel_BarTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PrimaryPanel_HomeLayout.createSequentialGroup()
                    .addGap(166, 166, 166)
                    .addComponent(jPanel_Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(15, 15, 15)))
        );
        PrimaryPanel_HomeLayout.setVerticalGroup(
            PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrimaryPanel_HomeLayout.createSequentialGroup()
                .addComponent(jPanel_BarTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_resizeLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_resizeRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_WorkSpaceAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_LeftBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel_resizeRightBottom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jLabel_resizeLeftBottom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jLabel_resizeBottom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PrimaryPanel_HomeLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jPanel_Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        getContentPane().add(PrimaryPanel_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //<editor-fold defaultstate="colapsed" desc="Events">
    private void jLabel_DragAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_DragAreaMousePressed
        // TODO add your handling code here:
        AxisY = evt.getY();
        AxisX = evt.getX();
    }//GEN-LAST:event_jLabel_DragAreaMousePressed

    private void jLabel_DragAreaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_DragAreaMouseDragged
        // TODO add your handling code here:
        AxisXScreen = evt.getXOnScreen();
        AxisYScreen = evt.getYOnScreen();
        this.setLocation(AxisXScreen - AxisX, AxisYScreen - AxisY);
    }//GEN-LAST:event_jLabel_DragAreaMouseDragged

    private void jLabel_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(1);
        PrimaryPanel_Home.setPreferredSize(screenSizeMinimize);

    }//GEN-LAST:event_jLabel_MinimizeMouseClicked

    private void jLabel_MaxRestoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MaxRestoreMouseClicked
        // TODO add your handling code here:
        if (!StatusMaximize) {
            this.setExtendedState(Home.MAXIMIZED_BOTH);
            PrimaryPanel_Home.setPreferredSize(screenSizeMaximize);
            StatusMaximize = true;
        } else {
            this.setExtendedState(Home.NORMAL);
            PrimaryPanel_Home.setPreferredSize(screenSizeMinimize);
            StatusMaximize = false;
        }
    }//GEN-LAST:event_jLabel_MaxRestoreMouseClicked

    private void jLabel_ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ExitButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_ExitButtonMouseClicked

    private void jLabel_AdminModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AdminModMouseClicked
        jPanel_WorkSpaceAdmin.setVisible(true);
    }//GEN-LAST:event_jLabel_AdminModMouseClicked

    private void jLabel_ButtonGetEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ButtonGetEmployeesMouseClicked
        DefaultTableModel modelTable = CreateModelTableEmployees();
        ResultSet RtSet = stDb.GenerateStatement_GetEmployees();
        jTable_TableAdminSQL.setDefaultRenderer(Object.class, new RenderImageTable());

        if (AuthVerify) {
            Object EmployeesData[] = new Object[11];
            try {
                while (RtSet.next()) {
                    EmployeesData[0] = String.valueOf(RtSet.getString("IdEmployees"));
                    EmployeesData[2] = String.valueOf(RtSet.getString("NameEmployees"));
                    EmployeesData[3] = String.valueOf(RtSet.getString("LastNameEmployees"));
                    EmployeesData[4] = String.valueOf(RtSet.getString("EmailEmployees"));
                    EmployeesData[5] = String.valueOf(RtSet.getString("PasswordEmployees"));
                    EmployeesData[6] = String.valueOf(RtSet.getString("PhoneEmployees"));
                    EmployeesData[7] = String.valueOf(RtSet.getString("StatusAdminEmployees"));
                    EmployeesData[8] = String.valueOf(RtSet.getString("StatusConnectionEmployees"));
                    EmployeesData[9] = String.valueOf(RtSet.getString("GenderEmployees"));
                    try {
                        byte[] images = RtSet.getBytes("ImageEmployees");
                        BufferedImage bfImages = null;
                        InputStream iStImage = new ByteArrayInputStream(images);
                        bfImages = ImageIO.read(iStImage);
                        ImageIcon iIcImages = new ImageIcon(bfImages.getScaledInstance(60, 60, 0));
                        EmployeesData[1] = new JLabel(iIcImages);
                    } catch (Exception e) {
                        EmployeesData[1] = "Sin Imagen";
                    }
                    modelTable.addRow(EmployeesData);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            jTable_TableAdminSQL.setModel(modelTable);
        } else {
            System.out.println("Flag Home: Action don't Allow - User Don't Logged");
        }
    }//GEN-LAST:event_jLabel_ButtonGetEmployeesMouseClicked

    private void jLabel_ButtonCleanTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ButtonCleanTableMouseClicked
        DefaultTableModel modelTable = CreateModelTableEmployees();
        for (int i = 0; i < jTable_TableAdminSQL.getRowCount(); i++) {
            modelTable.removeRow(i);
            i -= 1;
        }
        jTable_TableAdminSQL.setModel(modelTable);
    }//GEN-LAST:event_jLabel_ButtonCleanTableMouseClicked

    private void jLabel_ButtonSetEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ButtonSetEmployeesMouseClicked
        // TODO add your handling code here:
        if (AuthVerify) {
            RegisterUser_form RegisterUser = new RegisterUser_form();
            RegisterUser.setVisible(true);
        } else {
            System.out.println("Flag Home: Action don't Allow - User Don't Logged");
        }
    }//GEN-LAST:event_jLabel_ButtonSetEmployeesMouseClicked

    private void jTable_TableAdminSQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_TableAdminSQLMouseClicked
        // TODO add your handling code here:
        int Row = jTable_TableAdminSQL.getSelectedRow();
        TableModel tableModel = jTable_TableAdminSQL.getModel();
        ValuePointSelectedDeleteTable = tableModel.getValueAt(Row, 0);
    }//GEN-LAST:event_jTable_TableAdminSQLMouseClicked

    private void jLabel_ButtonDeleteEntitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ButtonDeleteEntitiesMouseClicked
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "Desea eliminar al Empleado/Usuario con ID: " + ValuePointSelectedDeleteTable + "?", "Eliminacion", JOptionPane.OK_CANCEL_OPTION, JOptionPane.DEFAULT_OPTION);
        if (input == 0) {
            stDb.GenerateStatement_DeleteEmplCl(ValuePointSelectedDeleteTable);
            JOptionPane.showMessageDialog(null, "eliminacion Satisfactoria");
        }
    }//GEN-LAST:event_jLabel_ButtonDeleteEntitiesMouseClicked

    private void jLabel_ButtonUpdateUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ButtonUpdateUserMouseClicked
        // TODO add your handling code here:
        if (AuthVerify) {
            UpdateUser_form UpdateUser = new UpdateUser_form();
            UpdateUser.setVisible(true);
        } else {
            System.out.println("Flag Home: Action don't Allow - User Don't Logged");
        }
    }//GEN-LAST:event_jLabel_ButtonUpdateUserMouseClicked

    private void jLabel_ButtonLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ButtonLogOutMouseClicked
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "¿Desea cerrar sesión?", "cerrar sesión", JOptionPane.OK_CANCEL_OPTION, JOptionPane.DEFAULT_OPTION);
        if (input == 0) {
            setVisible(false);
            Login login = new Login();
            login.setVisible(true);
            stDb.setAuthVerify(false);
        }
    }//GEN-LAST:event_jLabel_ButtonLogOutMouseClicked

    private void jLabel_ButtonGenerateReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ButtonGenerateReportMouseClicked
        // TODO add your handling code here:
        GenerateReport GR = new GenerateReport();
        GR.GenerateReport_EmployeesLogs();
    }//GEN-LAST:event_jLabel_ButtonGenerateReportMouseClicked
    
    //</editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PrimaryPanel_Home;
    private javax.swing.JLabel jLabel_AcconuntingModLabel;
    private javax.swing.JLabel jLabel_AccountingMod;
    private javax.swing.JLabel jLabel_AdminMod;
    private javax.swing.JLabel jLabel_AdminModLabel;
    private javax.swing.JLabel jLabel_ButtonCleanTable;
    private javax.swing.JLabel jLabel_ButtonDeleteEntities;
    private javax.swing.JLabel jLabel_ButtonGenerateReport;
    private javax.swing.JLabel jLabel_ButtonGetEmployees;
    private javax.swing.JLabel jLabel_ButtonLogOut;
    private javax.swing.JLabel jLabel_ButtonSetEmployees;
    private javax.swing.JLabel jLabel_ButtonUpdateUser;
    private javax.swing.JLabel jLabel_DragArea;
    private javax.swing.JLabel jLabel_ExitButton;
    private javax.swing.JLabel jLabel_InventoryMod;
    private javax.swing.JLabel jLabel_InvetoryModLabel;
    private javax.swing.JLabel jLabel_LevelAdmin;
    private javax.swing.JLabel jLabel_LogoScarab;
    private javax.swing.JLabel jLabel_LogoWelcome;
    private javax.swing.JLabel jLabel_MaxRestore;
    private javax.swing.JLabel jLabel_Minimize;
    private javax.swing.JLabel jLabel_NameUser;
    private javax.swing.JLabel jLabel_SubtitleWelcome;
    private javax.swing.JLabel jLabel_TitleWelcome;
    private javax.swing.JLabel jLabel_resizeBottom;
    private javax.swing.JLabel jLabel_resizeLeft;
    private javax.swing.JLabel jLabel_resizeLeftBottom;
    private javax.swing.JLabel jLabel_resizeRight;
    private javax.swing.JLabel jLabel_resizeRightBottom;
    private javax.swing.JPanel jPanel_BarToolAdmin;
    private javax.swing.JPanel jPanel_BarTop;
    private javax.swing.JPanel jPanel_LeftBar;
    private javax.swing.JPanel jPanel_SpaceAdmin;
    private javax.swing.JPanel jPanel_Welcome;
    private javax.swing.JPanel jPanel_WorkSpaceAdmin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator_UserLeverRootDiv;
    private javax.swing.JTable jTable_TableAdminSQL;
    // End of variables declaration//GEN-END:variables
}
