package view.Home;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import model.ModAdmin.ModAdmin;

/**
 *
 * @author RODX
 */
public class Home extends javax.swing.JFrame {
    
    /**
     * variables declarated from the class - RODX
     */
    boolean StatusMaximize = false;
    public Toolkit tK = Toolkit.getDefaultToolkit();
    public Dimension screenSizeMaximize = Toolkit.getDefaultToolkit().getScreenSize(), screenSizeMinimize;
    protected ModAdmin ModAdminActived = new ModAdmin();
    protected int AxisX, AxisY, AxisXScreen, AxisYScreen;
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.screenSizeMinimize = PrimaryPanel_Home.getPreferredSize();
    }

    @Override
    public Image getIconImage (){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images\\Icons\\1x\\IsoT\\IconBase-Default.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrimaryPanel_Home = new javax.swing.JPanel();
        jLabel_resizeRight = new javax.swing.JLabel();
        jLabel_resizeLeft = new javax.swing.JLabel();
        jLabel_resizeBottom = new javax.swing.JLabel();
        jLabel_resizeRightBottom = new javax.swing.JLabel();
        jLabel_resizeLeftBottom = new javax.swing.JLabel();
        jPanel_BarTop = new javax.swing.JPanel();
        jLabel_ExitButton = new javax.swing.JLabel();
        jLabel_MaxRestore = new javax.swing.JLabel();
        jLabel_Minimize = new javax.swing.JLabel();
        jLabel_DragArea = new javax.swing.JLabel();
        jLabel_LogoScarab = new javax.swing.JLabel();
        jPanel_LeftBar = new javax.swing.JPanel();
        jLabel_ImageUser = new javax.swing.JLabel();
        jLabel_NameUser = new javax.swing.JLabel();
        jSeparator_UserLeverRootDiv = new javax.swing.JSeparator();
        jLabel_LevelAdmin = new javax.swing.JLabel();
        jLabel_AccountingMod = new javax.swing.JLabel();
        jLabel_InventoryMod = new javax.swing.JLabel();
        jLabel_AdminMod = new javax.swing.JLabel();
        jLabel_AcconuntingModLabel = new javax.swing.JLabel();
        jLabel_InvetoryModLabel = new javax.swing.JLabel();
        jLabel_AdminModLabel = new javax.swing.JLabel();
        jPanel_WorkSpaceAdmin = new javax.swing.JPanel();
        jPanel_BarToolAdmin = new javax.swing.JPanel();
        jPanel_SpaceAdmin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scarab - Home");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(1980, 1080));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Home"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PrimaryPanel_Home.setBackground(new java.awt.Color(51, 51, 51));
        PrimaryPanel_Home.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(102, 102, 102)));
        PrimaryPanel_Home.setMaximumSize(new java.awt.Dimension(1920, 1080));
        PrimaryPanel_Home.setMinimumSize(new java.awt.Dimension(1110, 730));
        PrimaryPanel_Home.setName("Home"); // NOI18N

        jLabel_resizeRight.setBackground(new java.awt.Color(102, 255, 255));
        jLabel_resizeRight.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));

        jLabel_resizeLeft.setBackground(new java.awt.Color(153, 255, 255));
        jLabel_resizeLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));

        jLabel_resizeBottom.setBackground(new java.awt.Color(153, 255, 255));
        jLabel_resizeBottom.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));

        jLabel_resizeRightBottom.setBackground(new java.awt.Color(0, 153, 153));
        jLabel_resizeRightBottom.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));

        jLabel_resizeLeftBottom.setBackground(new java.awt.Color(0, 153, 153));
        jLabel_resizeLeftBottom.setCursor(new java.awt.Cursor(java.awt.Cursor.SW_RESIZE_CURSOR));

        jPanel_BarTop.setBackground(new java.awt.Color(38, 38, 38));
        jPanel_BarTop.setAutoscrolls(true);
        jPanel_BarTop.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel_ExitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ExitButton.setText("X");
        jLabel_ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ExitButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ExitButtonMouseExited(evt);
            }
        });

        jLabel_MaxRestore.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_MaxRestore.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_MaxRestore.setText("❐");
        jLabel_MaxRestore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MaxRestoreMouseClicked(evt);
            }
        });

        jLabel_Minimize.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Minimize.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Minimize.setText("-");
        jLabel_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MinimizeMouseClicked(evt);
            }
        });

        jLabel_DragArea.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel_DragAreaMouseDragged(evt);
            }
        });
        jLabel_DragArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_DragAreaMousePressed(evt);
            }
        });

        jLabel_LogoScarab.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel_LogoScarab.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_LogoScarab.setIcon(new javax.swing.ImageIcon("E:\\Programacion\\JavaProjets\\SysScarab\\src\\main\\resources\\images\\Icons\\1x\\IsoT\\Icon-20px.png")); // NOI18N
        jLabel_LogoScarab.setText("SCARAB");
        jLabel_LogoScarab.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        javax.swing.GroupLayout jPanel_BarTopLayout = new javax.swing.GroupLayout(jPanel_BarTop);
        jPanel_BarTop.setLayout(jPanel_BarTopLayout);
        jPanel_BarTopLayout.setHorizontalGroup(
            jPanel_BarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BarTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_LogoScarab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_DragArea, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Minimize)
                .addGap(18, 18, 18)
                .addComponent(jLabel_MaxRestore)
                .addGap(18, 18, 18)
                .addComponent(jLabel_ExitButton)
                .addGap(18, 18, 18))
        );
        jPanel_BarTopLayout.setVerticalGroup(
            jPanel_BarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BarTopLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_LogoScarab)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BarTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_BarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_MaxRestore)
                        .addComponent(jLabel_ExitButton)
                        .addComponent(jLabel_Minimize))
                    .addComponent(jLabel_DragArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel_LeftBar.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_LeftBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_ImageUser.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_ImageUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ImageUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ImageUser.setText("ImageProfileUnloaded");
        jLabel_ImageUser.setOpaque(true);

        jLabel_NameUser.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_NameUser.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        jLabel_NameUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NameUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_NameUser.setText("User");

        jSeparator_UserLeverRootDiv.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_LevelAdmin.setFont(new java.awt.Font("Roboto Mono Thin", 2, 12)); // NOI18N
        jLabel_LevelAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_LevelAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_LevelAdmin.setText("StatusAdmim");

        jLabel_AccountingMod.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_AccountingMod.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_AccountingMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_AccountingMod.setIcon(new javax.swing.ImageIcon("E:\\Programacion\\JavaProjets\\SysScarab\\src\\main\\resources\\images\\Icons\\1x\\IconAccounting.png")); // NOI18N

        jLabel_InventoryMod.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_InventoryMod.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_InventoryMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_InventoryMod.setIcon(new javax.swing.ImageIcon("E:\\Programacion\\JavaProjets\\SysScarab\\src\\main\\resources\\images\\Icons\\1x\\IconInventoy.png")); // NOI18N

        jLabel_AdminMod.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_AdminMod.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_AdminMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_AdminMod.setIcon(new javax.swing.ImageIcon("E:\\Programacion\\JavaProjets\\SysScarab\\src\\main\\resources\\images\\Icons\\1x\\IconManagement.png")); // NOI18N
        jLabel_AdminMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_AdminModMouseClicked(evt);
            }
        });

        jLabel_AcconuntingModLabel.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_AcconuntingModLabel.setForeground(new java.awt.Color(153, 255, 153));
        jLabel_AcconuntingModLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_AcconuntingModLabel.setText("Contabilidad");

        jLabel_InvetoryModLabel.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_InvetoryModLabel.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_InvetoryModLabel.setForeground(new java.awt.Color(204, 153, 255));
        jLabel_InvetoryModLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_InvetoryModLabel.setText("Inventario");

        jLabel_AdminModLabel.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_AdminModLabel.setForeground(new java.awt.Color(255, 153, 153));
        jLabel_AdminModLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_AdminModLabel.setText("Administracion");

        javax.swing.GroupLayout jPanel_LeftBarLayout = new javax.swing.GroupLayout(jPanel_LeftBar);
        jPanel_LeftBar.setLayout(jPanel_LeftBarLayout);
        jPanel_LeftBarLayout.setHorizontalGroup(
            jPanel_LeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LeftBarLayout.createSequentialGroup()
                .addGroup(jPanel_LeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_LeftBarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel_LeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_InventoryMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_AccountingMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_ImageUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_NameUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator_UserLeverRootDiv, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_LevelAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_AdminMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_AcconuntingModLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_AdminModLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel_LeftBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_InvetoryModLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        jPanel_LeftBarLayout.setVerticalGroup(
            jPanel_LeftBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LeftBarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel_ImageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_NameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator_UserLeverRootDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_LevelAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel_AccountingMod, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_AcconuntingModLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_InventoryMod, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_InvetoryModLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_AdminMod, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_AdminModLabel)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel_WorkSpaceAdmin.setBackground(new java.awt.Color(51, 51, 51));

        jPanel_BarToolAdmin.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_BarToolAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel_BarToolAdminLayout = new javax.swing.GroupLayout(jPanel_BarToolAdmin);
        jPanel_BarToolAdmin.setLayout(jPanel_BarToolAdminLayout);
        jPanel_BarToolAdminLayout.setHorizontalGroup(
            jPanel_BarToolAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_BarToolAdminLayout.setVerticalGroup(
            jPanel_BarToolAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        jPanel_SpaceAdmin.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_SpaceAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel_SpaceAdminLayout = new javax.swing.GroupLayout(jPanel_SpaceAdmin);
        jPanel_SpaceAdmin.setLayout(jPanel_SpaceAdminLayout);
        jPanel_SpaceAdminLayout.setHorizontalGroup(
            jPanel_SpaceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_SpaceAdminLayout.setVerticalGroup(
            jPanel_SpaceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_WorkSpaceAdminLayout = new javax.swing.GroupLayout(jPanel_WorkSpaceAdmin);
        jPanel_WorkSpaceAdmin.setLayout(jPanel_WorkSpaceAdminLayout);
        jPanel_WorkSpaceAdminLayout.setHorizontalGroup(
            jPanel_WorkSpaceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_BarToolAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_SpaceAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_WorkSpaceAdminLayout.setVerticalGroup(
            jPanel_WorkSpaceAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_WorkSpaceAdminLayout.createSequentialGroup()
                .addComponent(jPanel_BarToolAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_SpaceAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PrimaryPanel_HomeLayout = new javax.swing.GroupLayout(PrimaryPanel_Home);
        PrimaryPanel_Home.setLayout(PrimaryPanel_HomeLayout);
        PrimaryPanel_HomeLayout.setHorizontalGroup(
            PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrimaryPanel_HomeLayout.createSequentialGroup()
                .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_resizeLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jLabel_resizeLeftBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrimaryPanel_HomeLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPanel_LeftBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_WorkSpaceAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PrimaryPanel_HomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_resizeBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_resizeRight, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_resizeRightBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jPanel_BarTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PrimaryPanel_HomeLayout.setVerticalGroup(
            PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrimaryPanel_HomeLayout.createSequentialGroup()
                .addComponent(jPanel_BarTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_resizeLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_resizeRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_WorkSpaceAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_LeftBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrimaryPanel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_resizeBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_resizeRightBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_resizeLeftBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(PrimaryPanel_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_DragAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_DragAreaMousePressed
        // TODO add your handling code here:
        AxisY = evt.getY();
        AxisX = evt.getX();
    }//GEN-LAST:event_jLabel_DragAreaMousePressed

    private void jLabel_DragAreaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_DragAreaMouseDragged
        // TODO add your handling code here:
        AxisXScreen = evt.getXOnScreen();
        AxisYScreen = evt.getYOnScreen();
        this.setLocation(AxisXScreen - AxisX, AxisYScreen - AxisY);
    }//GEN-LAST:event_jLabel_DragAreaMouseDragged

    private void jLabel_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(1);
        
        if(!StatusMaximize){
            PrimaryPanel_Home.setPreferredSize(screenSizeMaximize);
        }
        else{
            PrimaryPanel_Home.setPreferredSize(screenSizeMinimize);
        }
    }//GEN-LAST:event_jLabel_MinimizeMouseClicked

    private void jLabel_MaxRestoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MaxRestoreMouseClicked
        // TODO add your handling code here:
        if(!StatusMaximize){
            this.setExtendedState(this.MAXIMIZED_BOTH);
            PrimaryPanel_Home.setPreferredSize(screenSizeMaximize);
            StatusMaximize = true;
        }
        else{
            this.setExtendedState(this.NORMAL);
            PrimaryPanel_Home.setPreferredSize(screenSizeMinimize);
            StatusMaximize = false;
        }
    }//GEN-LAST:event_jLabel_MaxRestoreMouseClicked

    private void jLabel_ExitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ExitButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ExitButtonMouseExited

    private void jLabel_ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ExitButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel_ExitButtonMouseClicked

    private void jLabel_AdminModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AdminModMouseClicked
        // TODO add your handling code here:
        ModAdminActived.ModAdmin_GetUsers();
        System.out.println("execute ModAdmin...");
        System.out.println("jLabel_AdminModMouseClicked Flag ID");
    }//GEN-LAST:event_jLabel_AdminModMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PrimaryPanel_Home;
    private javax.swing.JLabel jLabel_AcconuntingModLabel;
    private javax.swing.JLabel jLabel_AccountingMod;
    private javax.swing.JLabel jLabel_AdminMod;
    private javax.swing.JLabel jLabel_AdminModLabel;
    private javax.swing.JLabel jLabel_DragArea;
    private javax.swing.JLabel jLabel_ExitButton;
    private javax.swing.JLabel jLabel_ImageUser;
    private javax.swing.JLabel jLabel_InventoryMod;
    private javax.swing.JLabel jLabel_InvetoryModLabel;
    private javax.swing.JLabel jLabel_LevelAdmin;
    private javax.swing.JLabel jLabel_LogoScarab;
    private javax.swing.JLabel jLabel_MaxRestore;
    private javax.swing.JLabel jLabel_Minimize;
    private javax.swing.JLabel jLabel_NameUser;
    private javax.swing.JLabel jLabel_resizeBottom;
    private javax.swing.JLabel jLabel_resizeLeft;
    private javax.swing.JLabel jLabel_resizeLeftBottom;
    private javax.swing.JLabel jLabel_resizeRight;
    private javax.swing.JLabel jLabel_resizeRightBottom;
    private javax.swing.JPanel jPanel_BarToolAdmin;
    private javax.swing.JPanel jPanel_BarTop;
    private javax.swing.JPanel jPanel_LeftBar;
    private javax.swing.JPanel jPanel_SpaceAdmin;
    private javax.swing.JPanel jPanel_WorkSpaceAdmin;
    private javax.swing.JSeparator jSeparator_UserLeverRootDiv;
    // End of variables declaration//GEN-END:variables
}
