/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Home.Forms.client;

import controller.db.StatementDbSQL;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.math.BigInteger;
import java.security.MessageDigest;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import view.textPrompt.TextPrompt;

/**
 *
 * @author RODX
 */
public class RegisterClient_form extends javax.swing.JFrame {
    
    
    //<editor-fold defaultstate="colapsed" desc="* Variables">
    protected StatementDbSQL newStatement = new StatementDbSQL();
    protected String ruta;
    protected boolean AuthVerify = newStatement.getAuthVerify();
    //</editor-fold>

    //<editor-fold defaultstate="colapsed" desc="** Methods">
    public RegisterClient_form() {
        if (AuthVerify) {
            initComponents();
            this.setLocationRelativeTo(null);

            //PlaceHolders
            TextPrompt PlaceholderId = new TextPrompt("Id/Identidicacion", jTextField_IdEmployees);
            TextPrompt PlaceholderName = new TextPrompt("Nombres Completos", jTextField_nameClient);
            TextPrompt PlaceholderLastName = new TextPrompt("Apellidos Completos", jTextField_LastNameClient);
            TextPrompt PlaceholderEmail = new TextPrompt("correo@dominio.com", jTextField_EmailClient);
            TextPrompt PlaceholderPassword = new TextPrompt("contraseña", jTextField_PassClient);
            TextPrompt PlaceholderAddress = new TextPrompt("cra 0 # 0 - null Complemento, Departamento, Ciudad", jTextField_AddressClient);
            TextPrompt PlaceholderPhone = new TextPrompt("3103103131", jTextField_PhoneClient);

            //Items ComboBoxs
            //Gender
            jComboBox_GenderClient.removeAllItems();
            jComboBox_GenderClient.addItem("M");
            jComboBox_GenderClient.addItem("F");
            jComboBox_GenderClient.addItem("I");
        } else {
            JOptionPane.showMessageDialog(null, "Accion no permitida: Usuario no loggeado");
            System.exit(0);
        }
    }

    private byte[] convertImage() {
        File image = new File(ruta);

        try {
            byte[] icon = new byte[(int) image.length()];
            InputStream input = new FileInputStream(image);
            input.read(icon);
            return icon;
        } catch (Exception e) {
            return null;
        }
    }
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrimaryPanel_FormRegisterUser = new javax.swing.JPanel();
        jPanel_registerEmployees = new javax.swing.JPanel();
        jLabel_Exit = new javax.swing.JLabel();
        jLabel_TitlePanelRE = new javax.swing.JLabel();
        jPanel_TextFieldsForm = new javax.swing.JPanel();
        jLabel_TFIdClient = new javax.swing.JLabel();
        jTextField_IdEmployees = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_TFNameClient = new javax.swing.JLabel();
        jTextField_nameClient = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_TFLastNameClient = new javax.swing.JLabel();
        jTextField_LastNameClient = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel_TFEmailClient = new javax.swing.JLabel();
        jTextField_EmailClient = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel_TFPassClient = new javax.swing.JLabel();
        jTextField_PassClient = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel_TFAddressClient = new javax.swing.JLabel();
        jTextField_AddressClient = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel_TFPhoneClient = new javax.swing.JLabel();
        jTextField_PhoneClient = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel_TFSGenderClient = new javax.swing.JLabel();
        jComboBox_GenderClient = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel_PerfilClient = new javax.swing.JLabel();
        jLabel_ButtonSelectImageClient = new javax.swing.JLabel();
        jLabel_imageLoadClient = new javax.swing.JLabel();
        jLabel_ButtonSaveDataClient = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setUndecorated(true);

        jPanel_registerEmployees.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_registerEmployees.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel_registerEmployees.setForeground(java.awt.Color.darkGray);

        jLabel_Exit.setText("X");
        jLabel_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ExitMouseClicked(evt);
            }
        });

        jLabel_TitlePanelRE.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel_TitlePanelRE.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_TitlePanelRE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TitlePanelRE.setText("Registro Cliente");

        jPanel_TextFieldsForm.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_TFIdClient.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_TFIdClient.setForeground(new java.awt.Color(36, 36, 36));
        jLabel_TFIdClient.setText("Id");

        jTextField_IdEmployees.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_IdEmployees.setBorder(null);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel_TFNameClient.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_TFNameClient.setForeground(new java.awt.Color(36, 36, 36));
        jLabel_TFNameClient.setText("Nombre");

        jTextField_nameClient.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_nameClient.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));

        jLabel_TFLastNameClient.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_TFLastNameClient.setForeground(new java.awt.Color(36, 36, 36));
        jLabel_TFLastNameClient.setText("Apellidos");

        jTextField_LastNameClient.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_LastNameClient.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));

        jLabel_TFEmailClient.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_TFEmailClient.setForeground(new java.awt.Color(36, 36, 36));
        jLabel_TFEmailClient.setText("Correo");

        jTextField_EmailClient.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_EmailClient.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));

        jLabel_TFPassClient.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_TFPassClient.setForeground(new java.awt.Color(36, 36, 36));
        jLabel_TFPassClient.setText("Contraseña");

        jTextField_PassClient.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_PassClient.setBorder(null);

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(102, 102, 102));

        jLabel_TFAddressClient.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_TFAddressClient.setForeground(new java.awt.Color(36, 36, 36));
        jLabel_TFAddressClient.setText("Direccion");

        jTextField_AddressClient.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_AddressClient.setBorder(null);

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(102, 102, 102));

        jLabel_TFPhoneClient.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_TFPhoneClient.setForeground(new java.awt.Color(36, 36, 36));
        jLabel_TFPhoneClient.setText("Telefono");

        jTextField_PhoneClient.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_PhoneClient.setBorder(null);

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(102, 102, 102));

        jLabel_TFSGenderClient.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_TFSGenderClient.setForeground(new java.awt.Color(36, 36, 36));
        jLabel_TFSGenderClient.setText("Genero");

        jComboBox_GenderClient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel_TextFieldsFormLayout = new javax.swing.GroupLayout(jPanel_TextFieldsForm);
        jPanel_TextFieldsForm.setLayout(jPanel_TextFieldsFormLayout);
        jPanel_TextFieldsFormLayout.setHorizontalGroup(
            jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TextFieldsFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TextFieldsFormLayout.createSequentialGroup()
                            .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_TextFieldsFormLayout.createSequentialGroup()
                                    .addComponent(jLabel_TFEmailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_EmailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel_TextFieldsFormLayout.createSequentialGroup()
                                    .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_TFNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_TFIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_IdEmployees, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_nameClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel_TextFieldsFormLayout.createSequentialGroup()
                                    .addComponent(jLabel_TFPassClient)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_PassClient, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_TextFieldsFormLayout.createSequentialGroup()
                                    .addComponent(jLabel_TFPhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_PhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_TextFieldsFormLayout.createSequentialGroup()
                                    .addComponent(jLabel_TFAddressClient, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_AddressClient, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_TextFieldsFormLayout.createSequentialGroup()
                                    .addComponent(jLabel_TFLastNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_LastNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator1)
                                .addComponent(jSeparator2)
                                .addComponent(jSeparator3)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(1, 1, 1)))
                    .addGroup(jPanel_TextFieldsFormLayout.createSequentialGroup()
                        .addComponent(jLabel_TFSGenderClient, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_GenderClient, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_TextFieldsFormLayout.setVerticalGroup(
            jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TextFieldsFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_IdEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TFIdClient))
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TFNameClient))
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_LastNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TFLastNameClient))
                .addGap(1, 1, 1)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_EmailClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TFEmailClient))
                .addGap(1, 1, 1)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_PassClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TFPassClient))
                .addGap(1, 1, 1)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_AddressClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TFAddressClient))
                .addGap(1, 1, 1)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_PhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TFPhoneClient))
                .addGap(1, 1, 1)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_TextFieldsFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TFSGenderClient)
                    .addComponent(jComboBox_GenderClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_PerfilClient.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_PerfilClient.setForeground(new java.awt.Color(36, 36, 36));
        jLabel_PerfilClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_PerfilClient.setText("Perfil");

        jLabel_ButtonSelectImageClient.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_ButtonSelectImageClient.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_ButtonSelectImageClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ButtonSelectImageClient.setText("seleccionar");
        jLabel_ButtonSelectImageClient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jLabel_ButtonSelectImageClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ButtonSelectImageClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ButtonSelectImageClientMouseClicked(evt);
            }
        });

        jLabel_imageLoadClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_imageLoadClient.setText("No Image");
        jLabel_imageLoadClient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_imageLoadClient, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_PerfilClient, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel_ButtonSelectImageClient, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_PerfilClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_ButtonSelectImageClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_imageLoadClient, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jLabel_ButtonSaveDataClient.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel_ButtonSaveDataClient.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_ButtonSaveDataClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ButtonSaveDataClient.setText("Registrar");
        jLabel_ButtonSaveDataClient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jLabel_ButtonSaveDataClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ButtonSaveDataClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ButtonSaveDataClientMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_registerEmployeesLayout = new javax.swing.GroupLayout(jPanel_registerEmployees);
        jPanel_registerEmployees.setLayout(jPanel_registerEmployeesLayout);
        jPanel_registerEmployeesLayout.setHorizontalGroup(
            jPanel_registerEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_registerEmployeesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_TitlePanelRE, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel_Exit)
                .addContainerGap())
            .addGroup(jPanel_registerEmployeesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_TextFieldsForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel_registerEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_registerEmployeesLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel_ButtonSaveDataClient, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_registerEmployeesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        jPanel_registerEmployeesLayout.setVerticalGroup(
            jPanel_registerEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_registerEmployeesLayout.createSequentialGroup()
                .addGroup(jPanel_registerEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_registerEmployeesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel_TitlePanelRE))
                    .addGroup(jPanel_registerEmployeesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Exit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_registerEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_TextFieldsForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_registerEmployeesLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_ButtonSaveDataClient)))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout PrimaryPanel_FormRegisterUserLayout = new javax.swing.GroupLayout(PrimaryPanel_FormRegisterUser);
        PrimaryPanel_FormRegisterUser.setLayout(PrimaryPanel_FormRegisterUserLayout);
        PrimaryPanel_FormRegisterUserLayout.setHorizontalGroup(
            PrimaryPanel_FormRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrimaryPanel_FormRegisterUserLayout.createSequentialGroup()
                .addComponent(jPanel_registerEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PrimaryPanel_FormRegisterUserLayout.setVerticalGroup(
            PrimaryPanel_FormRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_registerEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrimaryPanel_FormRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrimaryPanel_FormRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="colapsed" desc="Event">
    private void jLabel_ButtonSelectImageClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ButtonSelectImageClientMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("jpg, png & gif", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(extensionFilter);
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            ruta = fileChooser.getSelectedFile().getAbsolutePath();
            Image fcImages = new ImageIcon(ruta).getImage();
            ImageIcon iIcFCImage = new ImageIcon(fcImages.getScaledInstance(jLabel_imageLoadClient.getWidth(), jLabel_imageLoadClient.getHeight(), 0));
            jLabel_imageLoadClient.setIcon(iIcFCImage);
            jLabel_imageLoadClient.setText("");
        }
    }//GEN-LAST:event_jLabel_ButtonSelectImageClientMouseClicked

    private void jLabel_ButtonSaveDataClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ButtonSaveDataClientMouseClicked
        String Id = jTextField_IdEmployees.getText(), Name = jTextField_nameClient.getText(), LastName = jTextField_LastNameClient.getText(), Email = jTextField_EmailClient.getText(), Password = jTextField_PassClient.getText(), Phone = jTextField_PhoneClient.getText(), Address = jTextField_AddressClient.getText();

        String sha1 = "";
        
	try {
            MessageDigest digest = MessageDigest.getInstance("SHA-1");
	    digest.reset();
	    digest.update(Password.getBytes("utf8"));
	    sha1 = String.format("%040x", new BigInteger(1, digest.digest()));
	} catch (Exception e){
	    e.printStackTrace();
	}
        
        Password = sha1;
        Object StatusAdmin = null, Gender = (String) jComboBox_GenderClient.getSelectedItem();
        StatusAdmin = "CL";

        newStatement.GenerateStatement_SetClient(Integer.parseInt(Id), convertImage(), Name, LastName, Email, Address, Password, Phone, StatusAdmin, Gender);
        JOptionPane.showMessageDialog(null, "Cliente Registrado");
        setVisible(false);
    }//GEN-LAST:event_jLabel_ButtonSaveDataClientMouseClicked

    private void jLabel_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ExitMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jLabel_ExitMouseClicked
    //</editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterClient_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterClient_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterClient_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterClient_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterClient_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PrimaryPanel_FormRegisterUser;
    private javax.swing.JComboBox<String> jComboBox_GenderClient;
    private javax.swing.JLabel jLabel_ButtonSaveDataClient;
    private javax.swing.JLabel jLabel_ButtonSelectImageClient;
    private javax.swing.JLabel jLabel_Exit;
    private javax.swing.JLabel jLabel_PerfilClient;
    private javax.swing.JLabel jLabel_TFAddressClient;
    private javax.swing.JLabel jLabel_TFEmailClient;
    private javax.swing.JLabel jLabel_TFIdClient;
    private javax.swing.JLabel jLabel_TFLastNameClient;
    private javax.swing.JLabel jLabel_TFNameClient;
    private javax.swing.JLabel jLabel_TFPassClient;
    private javax.swing.JLabel jLabel_TFPhoneClient;
    private javax.swing.JLabel jLabel_TFSGenderClient;
    private javax.swing.JLabel jLabel_TitlePanelRE;
    private javax.swing.JLabel jLabel_imageLoadClient;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_TextFieldsForm;
    private javax.swing.JPanel jPanel_registerEmployees;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField_AddressClient;
    private javax.swing.JTextField jTextField_EmailClient;
    private javax.swing.JTextField jTextField_IdEmployees;
    private javax.swing.JTextField jTextField_LastNameClient;
    private javax.swing.JTextField jTextField_PassClient;
    private javax.swing.JTextField jTextField_PhoneClient;
    private javax.swing.JTextField jTextField_nameClient;
    // End of variables declaration//GEN-END:variables
}
